CREATE TABLE `user`(
    `id` INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `login` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);
ALTER TABLE `user` ADD UNIQUE INDEX `idx_user_email` (`email`);
ALTER TABLE `user` ADD UNIQUE INDEX `idx_user_login` (`login`);